{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from google.cloud import bigquery\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Especifique o caminho para o arquivo JSON de credenciais\n",
    "credencial = r\"C:\\Users\\Note reserva\\Downloads\\pythonengenharia-e4145aaaeb10.json\"\n",
    "\n",
    "# Crie um cliente BigQuery usando as credenciais\n",
    "client = bigquery.Client.from_service_account_json(credencial)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Note reserva\\Desktop\\Curso Engenharia Dados\\Python - SGBDS\\sgbds\\Lib\\site-packages\\google\\cloud\\bigquery\\table.py:1820: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>first_name</th>\n",
       "      <th>last_name</th>\n",
       "      <th>email</th>\n",
       "      <th>state</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>18</td>\n",
       "      <td>Jair</td>\n",
       "      <td>Magalhães</td>\n",
       "      <td>jair@exemplo.com</td>\n",
       "      <td>Alagoas</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>80</td>\n",
       "      <td>Daniela</td>\n",
       "      <td>Góes</td>\n",
       "      <td>daniela@usuario.com</td>\n",
       "      <td>Alagoas</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>83</td>\n",
       "      <td>Frida</td>\n",
       "      <td>Freire</td>\n",
       "      <td>None</td>\n",
       "      <td>Alagoas</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>23</td>\n",
       "      <td>Maria</td>\n",
       "      <td>Pires</td>\n",
       "      <td>None</td>\n",
       "      <td>Amazonas</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>69</td>\n",
       "      <td>Gustavo</td>\n",
       "      <td>Cardoso</td>\n",
       "      <td>gustavo@teste.com</td>\n",
       "      <td>Amazonas</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>16</td>\n",
       "      <td>Laura</td>\n",
       "      <td>Santos</td>\n",
       "      <td>laura@exemplo.com</td>\n",
       "      <td>Maranhão</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>22</td>\n",
       "      <td>Heitor</td>\n",
       "      <td>Pereira</td>\n",
       "      <td>None</td>\n",
       "      <td>Maranhão</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>39</td>\n",
       "      <td>Caio</td>\n",
       "      <td>Batista</td>\n",
       "      <td>caio@usuario.com</td>\n",
       "      <td>Maranhão</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>46</td>\n",
       "      <td>Rafael</td>\n",
       "      <td>Freire</td>\n",
       "      <td>rafael@exemplo.com</td>\n",
       "      <td>Maranhão</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>57</td>\n",
       "      <td>Stephanie</td>\n",
       "      <td>Barboza</td>\n",
       "      <td>stephanie@meu_email.com</td>\n",
       "      <td>Maranhão</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>74</td>\n",
       "      <td>Júlia</td>\n",
       "      <td>Almeida</td>\n",
       "      <td>júlia@meu_email.com</td>\n",
       "      <td>Maranhão</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>19</td>\n",
       "      <td>Caíque</td>\n",
       "      <td>Monteiro</td>\n",
       "      <td>caíque@exemplo.com</td>\n",
       "      <td>Piauí</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>56</td>\n",
       "      <td>Cristiano</td>\n",
       "      <td>Fagundes</td>\n",
       "      <td>cristiano@usuario.com</td>\n",
       "      <td>Piauí</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>94</td>\n",
       "      <td>Cristiano</td>\n",
       "      <td>Pereira</td>\n",
       "      <td>cristiano@meu_email.com</td>\n",
       "      <td>Piauí</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>49</td>\n",
       "      <td>Júlia</td>\n",
       "      <td>Sousa</td>\n",
       "      <td>júlia@exemplo.com</td>\n",
       "      <td>Rondônia</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    id first_name  last_name                    email     state\n",
       "0   18       Jair  Magalhães         jair@exemplo.com   Alagoas\n",
       "1   80    Daniela       Góes      daniela@usuario.com   Alagoas\n",
       "2   83      Frida     Freire                     None   Alagoas\n",
       "3   23      Maria      Pires                     None  Amazonas\n",
       "4   69    Gustavo    Cardoso        gustavo@teste.com  Amazonas\n",
       "5   16      Laura     Santos        laura@exemplo.com  Maranhão\n",
       "6   22     Heitor    Pereira                     None  Maranhão\n",
       "7   39       Caio    Batista         caio@usuario.com  Maranhão\n",
       "8   46     Rafael     Freire       rafael@exemplo.com  Maranhão\n",
       "9   57  Stephanie    Barboza  stephanie@meu_email.com  Maranhão\n",
       "10  74      Júlia    Almeida      júlia@meu_email.com  Maranhão\n",
       "11  19     Caíque   Monteiro       caíque@exemplo.com     Piauí\n",
       "12  56  Cristiano   Fagundes    cristiano@usuario.com     Piauí\n",
       "13  94  Cristiano    Pereira  cristiano@meu_email.com     Piauí\n",
       "14  49      Júlia      Sousa        júlia@exemplo.com  Rondônia"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Construa sua consulta\n",
    "query = \"\"\" \n",
    "\n",
    "  SELECT \n",
    "  id\n",
    "  ,first_name\n",
    "  ,last_name\n",
    "  ,email  \n",
    "  ,state\n",
    " FROM `pythonengenharia.ProjetoPython.Clientes` \n",
    " where state in ('Piauí','Alagoas','Amazonas','Maranhão','Rondônia')\n",
    "\n",
    "\"\"\"\n",
    "# Execute a consulta\n",
    "resultado = client.query(query)\n",
    "\n",
    "# Converta os resultados em um DataFrame\n",
    "df = resultado.to_dataframe()\n",
    "df.head(30)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "sgbds",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
